### ISSUE TITLE
How can we work w files over 25Mb

### ISSUE THREAD

**Issue by aycajr** [perfect-everything/Speech-to-text_OpenAI_Whisper_Python#1]
is there a way to work w files over 25Mb? I have tried to adjust the code from 25 to 50 but it didn't work... thanks

**Comment by perfect-everything** [comment]
https://platform.openai.com/docs/guides/speech-to-text/longer-inputs
You can refer to this openai official document. Honestly I 'm not really good at coding lol. So if you can add this function into the code, please submit a PR.
